[build]
publish = "public"

[dev]
publish = "public"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/mcp"
to = "/.netlify/functions/express-mcp-server"
status = 200
force = true

[[redirects]]
from = "/.well-known/oauth-protected-resource"
to = "/.netlify/functions/express-mcp-server"
status = 200
force = true



[template.environment]
DESCOPE_PROJECT_ID = "Your Descope Project ID"
DESCOPE_BASE_URL = "Your Descope Base URL (e.g: `https://api.descope.com`)"
DESCOPE_MANAGEMENT_KEY = "Your Descope Management Key"
SERVER_URL = "Your Server URL (the URL of your Netlify project, you can configure after project is created)"
